/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupomc426.GUI;

import com.grupomc426.DataBase.*;
import com.grupomc426.API.*;
import com.grupomc426.Targets.Usuarios.Pessoa;
import com.grupomc426.Targets.Usuarios.Usuario;

/**
 *
 * @author cauan-newton
 */
public class MenuCadastro extends javax.swing.JFrame {

    /**
     * Creates new form MenuCadastro
     */
    public MenuCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        botaoConfirmar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        tipoCadastro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        usuarioCadastro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        senhaCadastro = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nascimentoCadastro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        telefoneCadastro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cpfCadastro = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu de Cadastro");

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        tipoCadastro
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente", "Enfermeiro", "Médico" }));
        tipoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCadastroActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuário");

        usuarioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCadastroActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo");

        senhaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCadastroActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha");

        jLabel6.setText("Ano de Nascimento");

        jLabel7.setText("Telefone");

        jLabel8.setText("CPF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup().addContainerGap(139, Short.MAX_VALUE).addComponent(jLabel1)
                                .addGap(136, 136, 136))
                .addGroup(layout.createSequentialGroup().addGap(29, 29, 29).addComponent(botaoConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltar).addGap(24, 24, 24))
                .addGroup(layout.createSequentialGroup().addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(senhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 186,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7).addComponent(jLabel2).addComponent(jLabel8)
                                                .addComponent(jLabel6))
                                        .addGap(79, 79, 79)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(usuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tipoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 186,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(telefoneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nascimentoCadastro,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 186,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 186,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addGap(29, 29, 29).addComponent(jLabel1).addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telefoneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel8)
                        .addComponent(cpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6)
                        .addComponent(nascimentoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
                        .addComponent(senhaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoConfirmar).addComponent(botaoVoltar))
                .addContainerGap(29, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    // TODO Adaptar para o runner depois
    public String botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {
        String usuario = usuarioCadastro.getText();
        String telefone = telefoneCadastro.getText();
        String cpf = cpfCadastro.getText();
        String nascimento = nascimentoCadastro.getText();
        String senha = senhaCadastro.getText();

        controladorProntuario prontuario = new controladorProntuario();

        Pessoa novaPessoa = new Pessoa(usuario, telefone, cpf, nascimento);
        Usuario novoUsuario = new Usuario(novaPessoa, senha, false);

        try {
            prontuario.operacaoCadastro(ACAO.ADICIONAR, novoUsuario);
            dispose();
            return "Ok";
        } catch (IllegalArgumentException erro) {
            String mensagem = erro.getMessage();
            TelaErroGenerica telaErro = new TelaErroGenerica(mensagem);
            telaErro.setVisible(true);
            return mensagem;
        } catch (Exception e) {
            // TODO Implementar Throws Banco de Dados
            TelaErroGenerica telaErro = new TelaErroGenerica("Falha ao conectar ao Banco de Dados!");
            telaErro.setVisible(true);
            return "Ok";
        }
    }

    private void tipoCadastroActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void usuarioCadastroActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void senhaCadastroActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField cpfCadastro;
    private javax.swing.JTextField nascimentoCadastro;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField senhaCadastro;
    private javax.swing.JTextField telefoneCadastro;
    private javax.swing.JComboBox<String> tipoCadastro;
    private javax.swing.JTextField usuarioCadastro;
    // End of variables declaration

    public javax.swing.JTextField getCpfCadastro() {
        return cpfCadastro;
    }

    public void setCpfCadastro(javax.swing.JTextField cpfCadastro) {
        this.cpfCadastro = cpfCadastro;
    }

    public javax.swing.JTextField getNascimentoCadastro() {
        return nascimentoCadastro;
    }

    public void setNascimentoCadastro(javax.swing.JTextField nascimentoCadastro) {
        this.nascimentoCadastro = nascimentoCadastro;
    }

    public javax.swing.JPasswordField getSenhaCadastro() {
        return senhaCadastro;
    }

    public void setSenhaCadastro(javax.swing.JPasswordField senhaCadastro) {
        this.senhaCadastro = senhaCadastro;
    }

    public javax.swing.JTextField getTelefoneCadastro() {
        return telefoneCadastro;
    }

    public void setTelefoneCadastro(javax.swing.JTextField telefoneCadastro) {
        this.telefoneCadastro = telefoneCadastro;
    }

    public javax.swing.JComboBox<String> getTipoCadastro() {
        return tipoCadastro;
    }

    public void setTipoCadastro(javax.swing.JComboBox<String> tipoCadastro) {
        this.tipoCadastro = tipoCadastro;
    }

    public javax.swing.JTextField getUsuarioCadastro() {
        return usuarioCadastro;
    }

    public void setUsuarioCadastro(javax.swing.JTextField usuarioCadastro) {
        this.usuarioCadastro = usuarioCadastro;
    }
}