/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupomc426.GUI;

import java.time.format.DateTimeFormatter;
import java.util.List;

import com.grupomc426.API.controladorConsulta;
import com.grupomc426.Targets.Atendimento.Consulta;
import com.grupomc426.Targets.Usuarios.Medico;
import com.grupomc426.Targets.Usuarios.Pessoa;
import com.grupomc426.Targets.Usuarios.Usuario;

/**
 *
 * @author Melanie
 */
public class TelaMinhasConsultas extends javax.swing.JFrame {

    private List<Consulta> consultas = null;
    private String consultaString = null;
    private Consulta consultaEscolhida = null;

    /**
     * Creates new form TelaMinhasConsultas
     */
    public TelaMinhasConsultas(Usuario user) {
        initComponents(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(Usuario user) {

        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton7 = new javax.swing.JToggleButton();

        jToggleButton3.setText("jToggleButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(user.getNome());

        jToggleButton1.setText("Sair");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        controladorConsulta controlador = new controladorConsulta();
        if (user.getEhFuncionario()) {
            Medico med = (Medico) user;
            consultas = controlador.obterConsultaMedico(med.getCrm());
        } else {
            consultas = controlador.obterConsultaPaciente(user.getCPF());
        }

        String[] listaConsultas = null;
        if (consultas != null && consultas.size() > 0 && user.getEhFuncionario()) {
            listaConsultas = new String[consultas.size()];
            int i = 0;
            for (Consulta cons : consultas) {
                listaConsultas[i] = "Paciente: " + cons.getUsuario().getNome() + " <> Data: "
                        + cons.getHorario().format(DateTimeFormatter.ofPattern("dd/MM/yyyy - HH:mm:ss"));
                i += 1;
            }
            consultaEscolhida = consultas.get(0);
        } else if (consultas != null && consultas.size() > 0) {
            listaConsultas = new String[consultas.size()];
            int i = 0;
            for (Consulta cons : consultas) {
                listaConsultas[i] = "Medico: " + cons.getMedico().getNome() + " <> Data: "
                        + cons.getHorario().format(DateTimeFormatter.ofPattern("dd/MM/yyyy - HH:mm:ss"));
                i += 1;
            }
            consultaEscolhida = consultas.get(0);
        } else {
            listaConsultas = new String[] { "Nao tem consultas" };
        }

        jLabel2.setText("Selecionar Consulta");

        jComboBox1.setModel(
                new javax.swing.DefaultComboBoxModel<>(listaConsultas));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaString = jComboBox1.getSelectedItem().toString();
                if (consultas != null) {
                    for (Consulta ex : consultas) {
                        if (consultaString.contains(ex.getMedico().getNome())) {
                            consultaEscolhida = ex;
                            break;
                        }
                    }
                }
            }
        });

        jToggleButton7.setText("Selecionar");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jToggleButton1))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jToggleButton7,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 94,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(146, 146, 146)
                                                                        .addComponent(jLabel2))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(164, 164, 164)
                                                                        .addComponent(jComboBox1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 150, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jToggleButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82,
                                        Short.MAX_VALUE)
                                .addComponent(jToggleButton1)
                                .addContainerGap()));

        pack();
    }// </editor-fold>

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        dispose();
    }

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        if (consultaEscolhida != null) {
            TelaConsulta novaConsulta = new TelaConsulta(consultaEscolhida);
            novaConsulta.setVisible(true);
    } else {
            TelaErroGenerica erro = new TelaErroGenerica("Consulta nao existente");
            erro.setVisible(true);
    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        Usuario user = new Usuario(new Pessoa("Darlan Pereira Matos", "70912345678", "01234567890", "1990"), "mock123",
                false);

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMinhasConsultas.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMinhasConsultas.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMinhasConsultas.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMinhasConsultas.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMinhasConsultas(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton7;
    // End of variables declaration
}
